/*
Copyright 2025 Pramod Bindal

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	pramodbindalv1alpha1 "github.com/pramodbindal/my-custom-labeler/pkg/apis/pramodbindal/v1alpha1"
	scheme "github.com/pramodbindal/my-custom-labeler/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LabelersGetter has a method to return a LabelerInterface.
// A group's client should implement this interface.
type LabelersGetter interface {
	Labelers(namespace string) LabelerInterface
}

// LabelerInterface has methods to work with Labeler resources.
type LabelerInterface interface {
	Create(ctx context.Context, labeler *pramodbindalv1alpha1.Labeler, opts v1.CreateOptions) (*pramodbindalv1alpha1.Labeler, error)
	Update(ctx context.Context, labeler *pramodbindalv1alpha1.Labeler, opts v1.UpdateOptions) (*pramodbindalv1alpha1.Labeler, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*pramodbindalv1alpha1.Labeler, error)
	List(ctx context.Context, opts v1.ListOptions) (*pramodbindalv1alpha1.LabelerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *pramodbindalv1alpha1.Labeler, err error)
	LabelerExpansion
}

// labelers implements LabelerInterface
type labelers struct {
	*gentype.ClientWithList[*pramodbindalv1alpha1.Labeler, *pramodbindalv1alpha1.LabelerList]
}

// newLabelers returns a Labelers
func newLabelers(c *PramodbindalV1alpha1Client, namespace string) *labelers {
	return &labelers{
		gentype.NewClientWithList[*pramodbindalv1alpha1.Labeler, *pramodbindalv1alpha1.LabelerList](
			"labelers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *pramodbindalv1alpha1.Labeler { return &pramodbindalv1alpha1.Labeler{} },
			func() *pramodbindalv1alpha1.LabelerList { return &pramodbindalv1alpha1.LabelerList{} },
		),
	}
}
